#!/usr/bin/env bash
set -euo pipefail

red='\033[0;31m'
green='\033[0;32m'
reset='\033[0m'

echored() {
  echo -e "${red}$@${reset}"
}

echogreen() {
  echo -e "${green}$@${reset}"
}

HALFPIPE_FILE_PATH="${HALFPIPE_FILE_PATH:-.halfpipe.io}"
HALFPIPE_ARGS=""
if [ -n "$HALFPIPE_FILE_PATH" ]; then
  HALFPIPE_ARGS="-i $HALFPIPE_FILE_PATH"
fi

echo
echogreen "* STEP 1/3: Updating halfpipe to latest version"
halfpipe sync
echo
halfpipe version
echo

echo
echogreen "* STEP 2/3: Running halfpipe"
halfpipe $HALFPIPE_ARGS

echo
echogreen "* STEP 3/3: Checking if workflow has changed"
if git diff -I '^# Generated using halfpipe' --quiet; then
  echo "synced=true" >> "$GITHUB_OUTPUT"
  echogreen "halfpipe manifest and workflow are in sync"
  exit 0
else 
  echo "synced=false" >> "$GITHUB_OUTPUT"
  echored "halfpipe manifest and workflow are not in sync"
  git diff -I '^# Generated using halfpipe'
fi
